server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone=GMT+8
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
# 日志
logging:
  # 级别
  level:
    # 根日志
    root: warn
    # 这个包下
    com.study.mapper: trace
  pattern:
    # 打印格式 %p日志级别 %m日志内容  %n换行
    console: '%p%m%n'